/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { MeshStandardMaterial } from 'three'

export default function Model(props) {

  
  // const customMaterial = new MeshStandardMaterial({
  //   color: 'green',
  //   roughness: 0.4,
  //   metalness: 0.5
  // })

  const group = React.useRef()
  const { scene, animations } = useGLTF(`${import.meta.env.BASE_URL}assets/model.gltf`)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  console.log(nodes)
console.log(materials)
  return (
    <group ref={group} {...props} dispose={null}>
      
      <group name="Scene">
        <group name="Armature_druide" scale={1.908}>
          <primitive object={nodes.root} />
          <skinnedMesh name="druid" geometry={nodes.druid.geometry} material={materials.color_main} skeleton={nodes.druid.skeleton} />
        </group>
      </group>
    </group>
    
  )
  
}

useGLTF(`${import.meta.env.BASE_URL}assets/scene.gltf`);

